"""English texts. Keys: usage.* (command usage, shown in !help), err.* (errors), msg.* (replies),
web.* (signup pages). Replies are Markdown. strings/de.py later mirrors the same keys.
Texts without parameters are returned as they are, so they may contain literal braces."""

STRINGS: dict[str, str] = {
    # --- usage (one line each, shown in !help) -----------------------------------------------
    "usage.help": "`!help`: the commands you can use",
    "usage.whoami": "`!whoami`: your roles",
    "usage.confirm": "`!confirm <code>`: run a plan I proposed",
    "usage.cancel": "`!cancel`: drop your pending plan or upload",
    "usage.admin.prof": "`!admin prof add|remove|list [@user]`: professor allowlist",
    "usage.admin.audit": "`!admin audit [n]`: recent audit entries",
    "usage.admin.bots": "`!admin bots pending|approve <id>|reject <id> [reason]|disable-all`: professor bots",
    "usage.course.create": '`!course create <code> "<title>" [--semester HS26] [--template <name>]`: new course space',
    "usage.course.list": "`!course list`: your courses",
    "usage.course.info": "`!course info <code>`: course details",
    "usage.course.ta": "`!course ta add|remove <code> @user`: appoint or remove a TA",
    "usage.course.archive": "`!course archive <code> [--kick-students] [--dry-run]`: make a course read-only",
    "usage.course.rollover": "`!course rollover <code> <new-semester>`: same course for a new semester",
    "usage.room.add": '`!room add <code> "<name>" [--private] [--topic "..."]`: add a room to a course',
    "usage.room.remove": '`!room remove <code> "<room>"`: take a room out of a course',
    "usage.invite": "`!invite <code> [--dry-run]` + emails (below the command or as a file): invite people",
    "usage.roster.sync": "`!roster sync <code> [--remove] [--dry-run]` + emails: compare a list with the course",
    "usage.groups.create": "`!groups create <code> <n>`: create n exercise group rooms",
    "usage.groups.assign": "`!groups assign <code> [--auto]` (+ CSV email,group[,role]): fill the groups",
    "usage.groups.post": "`!groups post <code>` + CSV group,message or email,message: post per group/student",
    "usage.template.export": "`!template export <code> [<name>]` or `--saved <name>`: save and download a layout",
    "usage.template.import": "`!template import <name> [--global]` + .yaml file: import a layout",
    "usage.template.list": "`!template list`: your and global templates",
    "usage.template.delete": "`!template delete <name> [--global]`: delete a template",
    "usage.signup.new": "`!signup new <email> [course]`: signup link for one person",
    "usage.signup.guest": "`!signup guest <email> <name> [course]`: signup link for a guest without unibas address",
    "usage.signup.list": "`!signup list [course]`: open signup links",
    "usage.signup.revoke": "`!signup revoke <email|@user>`: invalidate open links",
    "usage.signup.renew": "`!signup renew <email|@user>`: new link, the old one stops working",
    "usage.signup.reset": "`!signup reset @user`: password-reset link",
    "usage.bot.create": "`!bot create <name>` + .mbp file: request your own bot",
    "usage.bot.update": "`!bot update <name>` + .mbp file: new plugin version",
    "usage.bot.list": "`!bot list`: your bots",
    "usage.bot.info": "`!bot info <name>`: bot status",
    "usage.bot.config": "`!bot config <name>`: get the config, or reply with it to a .yaml to replace it",
    "usage.bot.start": "`!bot start <name>`: start a bot",
    "usage.bot.stop": "`!bot stop <name>`: stop a bot",
    "usage.bot.delete": "`!bot delete <name>`: delete a bot and its account",
    # --- errors -------------------------------------------------------------------------------
    "err.not_dm": "Please send me commands in a direct chat with only you and me.",
    "err.forbidden": "You are not allowed to do that.",
    "err.internal": "Something went wrong. The details are in the bot log.",
    "err.matrix": "The server refused: {detail}",
    "err.check_failed": "This is unavailable right now (startup check failed: {check}). An admin has been notified.",
    "err.bad_args": "I couldn't read the arguments. Usage: {usage}",
    "err.unknown_flag": "Unknown option {flag}. Usage: {usage}",
    "err.bad_user": "'{value}' is not a user of this server (expected @name:{server}).",
    "err.user_not_found": "{user_id} has no account.",
    "err.account_exists": "{user_id} already has an account.",
    "err.unknown_course": "There is no course '{code}'.",
    "err.course_exists": "The course code {code} is already taken.",
    "err.course_code": "'{code}' is not a valid course code (letters, digits, . _ -, max 32).",
    "err.semester": "'{semester}' is not a semester. Use e.g. HS26 or FS27.",
    "err.same_semester": "The course is already in {semester}.",
    "err.course_archived": "{code} is already archived.",
    "err.ta_is_owner": "The course owner can't also be a TA.",
    "err.not_ta": "{user_id} is not a TA of {code}.",
    "err.room_unknown": "{code} has no room '{name}'.",
    "err.confirm_unknown": "No pending plan with code {code} (it may have expired).",
    "err.email_invalid": "'{value}' is not an email address.",
    "err.email_domain": "'{value}' is not a university address.",
    "err.email_chars": "'{value}' contains characters that can't be used in a username.",
    "err.email_reserved": "'{value}' maps to a reserved username.",
    "err.guest_name": "'{value}' can't be used as a guest name (letters, digits, . _ - only).",
    "err.no_valid_emails": "I found no usable university email addresses. Not usable: {invalid}",
    "err.no_open_link": "{user_id} has no open signup link.",
    "err.no_public_url": "signup.public_base_url is not configured; I can't create links.",
    "err.reset_self": "I can't reset my own password.",
    "err.csv_empty": "The file is empty.",
    "err.csv_missing_column": "The CSV has no '{column}' column.",
    "err.csv_role": "Unknown role '{value}' (use student or ta).",
    "err.group_number": "'{value}' is not a group number.",
    "err.group_count": "Create between 1 and {max} groups at a time.",
    "err.no_groups": "{code} has no group rooms yet (`!groups create`).",
    "err.no_students": "{code} has no students yet.",
    "err.nothing_to_assign": "Nothing to assign.",
    "err.nothing_to_post": "Nothing to post.",
    "err.file_missing": "That message has no file.",
    "err.file_too_large": "The file is too large (max {mb} MB).",
    "err.template_invalid": "The template is invalid: {detail}",
    "err.template_unknown": "There is no template '{name}'.",
    "err.template_name": "'{name}' is not a valid template name (letters, digits, . _ -).",
    "err.template_empty_course": "The course has no rooms to export.",
    "err.yaml_invalid": "That is not valid YAML: {detail}",
    "err.bots_disabled": "Professor bots are not enabled on this server.",
    "err.bot_name": "Bot names: lowercase letters, digits and -, max 24 characters.",
    "err.bot_exists": "You already have a bot called {name}.",
    "err.bot_unknown": "There is no bot {name}.",
    "err.bot_quota": "You have reached the limit of {limit} bots.",
    "err.bot_unchanged": "{name} already runs exactly this package.",
    "err.bot_request_unknown": "There is no pending bot request #{id}.",
    "err.mbp_invalid": "That is not a usable maubot plugin: {detail}",
    "err.mbp_dependencies": "The plugin needs Python packages that this server doesn't have: {deps}. Ask an admin.",
    "err.plugin_taken": "The plugin ID {plugin_id} belongs to someone else. Use your own ID in maubot.yaml.",
    "err.userbots_api": "The bot server answered {status}: {detail}",
    # --- replies ------------------------------------------------------------------------------
    "msg.yes": "yes",
    "msg.no": "no",
    "msg.and_more": " and {n} more",
    "msg.help_header": "**Commands**",
    "msg.help_footer": "Bulk changes are shown first and only run after `!confirm <code>`.",
    "msg.subcommands": "`!{name}` needs a subcommand:\n{usages}",
    "msg.whoami": "You are {user_id}.\nRoles: {roles}\nCourses: {courses}",
    "msg.plan": "{summary}\n\nRun it with `!confirm {code}` or drop it with `!cancel` (valid for {minutes} minutes).",
    "msg.dry_run": "{summary}\n\n_Dry run: nothing was changed._",
    "msg.cancelled": "Cancelled.",
    "msg.nothing_to_cancel": "There was nothing to cancel.",
    "msg.waiting_for_file": "Send the file now (within {minutes} minutes), or `!cancel`.",
    "msg.job_started": "Job #{id} started: 0 / {total}",
    "msg.job_progress": "Job #{id}: {done} / {total} done, {failed} failed",
    "msg.job_done": "Job #{id} finished: {done} of {total} done, {failed} failed.",
    "msg.job_done_instantly": "Done (job #{id}).",
    "msg.job_finish_failed": "Job #{id}: the final step failed: {error}",
    "msg.job_start_failed": "Job #{id}: the first step failed: {error}\nLinks that were created can be sent again with `!signup list` and `!signup renew`.",
    "msg.invalid_entries": "Not usable: {entries}",
    "msg.check_ok": "Startup check **{check}**: ok",
    "msg.check_failed": "Startup check **{check}** FAILED: {detail}",
    "msg.password_reset_notice": "Your password was just reset with a link from {admin}. All your sessions were logged out. If you didn't ask for this, contact an admin right away.",
    # admin
    "msg.prof_list": "**Professors**\n{users}",
    "msg.prof_added": "{user_id} is now a professor.",
    "msg.prof_already": "{user_id} was already a professor.",
    "msg.prof_removed": "{user_id} is no longer a professor. Their courses stay as they are.",
    "msg.prof_not_listed": "{user_id} was not on the list.",
    "msg.prof_in_config": "Note: {user_id} is also in the instance config `professors:` and comes back on the next restart.",
    "msg.audit_list": "**Audit log**\n{entries}",
    # courses and rooms
    "msg.course_creating": "Creating {code}, this takes a few seconds ...",
    "msg.course_created": "Course **{code}** is ready: {link}\nRooms: {rooms}\nAppoint TAs with `!course ta add {code} @user`, invite students with `!invite {code}`.",
    "msg.course_list": "**Courses**\n{courses}",
    "msg.archived_marker": " [archived]",
    "msg.course_info": "**{code}** {title} ({semester})\nOwner: {owner}\nTAs: {tas}\nStudents (joined or invited): {students}\nRooms: {rooms}\nOpen signup links: {links}\nArchived: {archived}\n{link}",
    "msg.ta_added": "{user_id} is now a TA of {code} and was invited to its rooms.",
    "msg.ta_removed": "{user_id} is no longer a TA of {code}.",
    "msg.kick_reason_ta": "No longer a TA of this course",
    "msg.kick_reason_archive": "Course archived",
    "msg.kick_reason_roster": "Not on the course list anymore",
    "msg.archive_plan": "Archive **{code}**: {rooms} rooms (incl. the space) become read-only for students and get an [Archiv] prefix.{kick}",
    "msg.archive_kick": " Students are removed.",
    "msg.rollover_done": "**{code}** for {semester} is ready: {link}\nThe previous course is now **{old_code}**. Archive it with `!course archive {old_code}`.",
    "msg.room_added": "Room **{name}** added to {code}.",
    "msg.room_removed": "**{name}** is no longer part of {code}. The room itself and its history still exist.",
    # invites, roster, groups
    "msg.invite_plan": "Invite to **{code}**: {existing} existing accounts get an invitation, {new} new people get a signup link (as CSV after confirming), {invalid} entries are not usable.",
    "msg.csv_delivery": "Here are the signup links for {count} new people. Send them with mail merge (Outlook/Word: column `link`), for example:\n\n> Hello, please create your account for the course chat: {{link}}\n> The link works once and expires in 14 days. Afterwards log in at {login_url}.",
    "msg.roster_summary": "Roster **{code}**: {listed} on the list, {unchanged} already in the course, {missing} missing, {extra} in the course but not on the list.",
    "msg.roster_missing": "Missing: {users}\nInvite them with `!invite {code}` and the same list.",
    "msg.roster_extra": "Not on the list: {users}",
    "msg.group_name": "Group {n}",
    "msg.group_name_format": "Group {n}",
    "msg.groups_create_plan": "Create {count} group rooms in **{code}** (Group {first} to Group {last}), staff invited.",
    "msg.groups_assign_plan": "Assign {count} people in **{code}**: {per_group}",
    "msg.groups_post_plan": "Send {count} messages for **{code}**. Preview:\n{preview}",
    # signup links
    "msg.inline_signup": "Signup link for **{user_id}** ({email}):\n{link}\n\nText to forward:\n> Please create your account for the DMI chat: {link}\n> The link works once. Afterwards log in at {login_url} as {user_id}.",
    "msg.inline_reset": "Password-reset link for **{user_id}** (valid 24 hours, works once):\n{link}\n\nOnly give it to the account owner. They will be notified when it is used.",
    "msg.signup_exists_invited": "{user_id} already has an account and was invited to {code}.",
    "msg.signup_list": "**Open signup links**\n{links}",
    "msg.signup_line": "- {user_id}, course {course}, expires {expires}, by {by}",
    "msg.signup_revoked": "{count} open link(s) of {user_id} revoked.",
    # templates
    "msg.template_exported": "Saved the layout of {code} as template `{name}`:",
    "msg.template_saved": "Template `{name}` saved ({scope}).",
    "msg.template_list": "**Templates**\n{templates}",
    "msg.template_deleted": "Template `{name}` deleted.",
    "msg.scope_personal": "personal",
    "msg.scope_global": "global",
    # professor bots
    "msg.bot_requested": "Request #{id} for bot **{name}** sent to the admins. I'll tell you when it's decided.",
    "msg.bot_provisioning": "Setting up bot **{name}** ...",
    "msg.bot_request_audit": "Bot request **#{id}** ({action}) from {owner}: `{name}`, plugin `{plugin_id}` v{version}, sha256 `{sha256}`, dependencies: {deps}\n`!admin bots approve {id}` or `!admin bots reject {id} [reason]`",
    "msg.bot_requests": "**Pending bot requests**\n{requests}",
    "msg.bot_request_line": "- #{id} {action} `{name}` by {owner}: `{plugin_id}` v{version}",
    "msg.bot_approved": "Request #{id} approved, job #{job} sets it up.",
    "msg.bot_rejected_admin": "Request #{id} rejected.",
    "msg.bot_rejected": "Your bot request **{name}** was rejected: {reason}",
    "msg.bot_ready": "Your bot **{name}** is running as {user_id}. Invite it to your room to use it.",
    "msg.bot_updated": "Bot **{name}** now runs version {version}.",
    "msg.bot_list": "**Bots**\n{bots}",
    "msg.bot_info": "**{name}** ({user_id})\nPlugin: `{plugin_id}` v{version}\nStatus: {status}\nRooms: {rooms}",
    "msg.bot_running": "running",
    "msg.bot_stopped": "stopped",
    "msg.bot_started": "Bot **{name}** started.",
    "msg.bot_stopped_now": "Bot **{name}** stopped.",
    "msg.bot_config_saved": "Config of **{name}** saved.",
    "msg.bot_delete_plan": "Delete bot **{name}**: its account {user_id} is deactivated and the bot removed.",
    "msg.bots_disabled_all": "Stopped {count} professor bots.",
    # --- signup pages ---------------------------------------------------------------------------
    "web.title": "DMI Matrix account",
    "web.signup.intro": "Create your account. Your username is:",
    "web.reset.intro": "Set a new password for:",
    "web.displayname": "Display name (optional)",
    "web.password": "Password",
    "web.password_confirm": "Repeat password",
    "web.password_hint": "At least {n} characters.",
    "web.submit.signup": "Create account",
    "web.submit.reset": "Set password",
    "web.reset.warning": "All your sessions will be logged out. Messages in encrypted rooms stay readable only if you have your recovery key.",
    "web.done": "Your account is ready.",
    "web.done_reset": "Your new password is set.",
    "web.username": "Username",
    "web.server": "Server",
    "web.done_hint": "Log in with Element or any Matrix app using this server and username.",
    "web.error.invalid": "This link is invalid or has expired. Ask for a new one.",
    "web.error.password_mismatch": "The passwords don't match.",
    "web.error.password_short": "The password must have at least {n} characters.",
    "web.error.rate_limited": "Too many attempts. Please try again later.",
    "web.error.generic": "Something went wrong. Please try again later.",
}
